### ISSUE TITLE
Penghapusan bagian yang tidak perlu

### ISSUE THREAD

**Issue by YamamotoShigekuni** [YamamotoShigekuni/kafekoding.github.io#2]
1. Menghilangkan menu blog pada navbar
2. Menghilangkan logo facebook pada mentor
3. Komen bagian uang kas pada bagian [Dashboard Admin](https://ilhamnopi.github.io/kafekoding.github.io/admin_template/dashboard.html)

**Comment by ViperRedBulLs** [comment]
take

**Comment by ViperRedBulLs** [comment]
FINISH
